server:
  port: 8000

spring:
  main:
    allow-bean-definition-overriding: true
  session:
    timeout: 60
  security:
    user:
      name: admin
      password: admin
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

datasource:
  url: jdbc:postgresql://localhost:5432/camunda-test
  username: postgres
  password: postgres
  
camunda:
  bpm:
    database:
      type: postgres
      schema-update: true
